<?php
    $order = $block->getOrder();
    $viewModel = $block->getData('view_model');
    $billing = $order->getBillingAddress();

    $orderItems = [];

foreach ($order->getAllVisibleItems() as $orderItem) {
    $item = [
        'page_id' => preg_replace("/[^a-zA-Z0-9-]/", "", $orderItem->getProduct()->getSku()),
        'product_name' => '"'.$orderItem->getName().'"',
        'quantity' => (int)$orderItem->getQtyOrdered(),
        'unit_price' => $orderItem->getPrice()
    ];

    $productType = $orderItem->getProduct()->getTypeId();

    if ($productType == 'configurable') {
        $item['page_id_variant'] = preg_replace("/[^a-zA-Z0-9-]/", "", $orderItem->getSku());
    }

    $orderItems []= $item;
}

    $orderItemsFlattened = json_encode($orderItems);
?>


<script src="//static.powerreviews.com/t/v1/tracker.js"></script>
<script>
    (function(){try{

    var tracker = POWERREVIEWS.tracker.createTracker({
        merchantGroupId: "<?= /* @noEscape */ $viewModel->getMerchantGroupId(); ?>"});

        var orderFeed = {
            merchantGroupId: "<?= /* @noEscape */ $viewModel->getMerchantGroupId(); ?>",
            merchantId: "<?= /* @noEscape */ $viewModel->getMerchantId(); ?>",
            locale: "<?= /* @noEscape */ $viewModel->getLocale(); ?>",
            marketingOptIn: true,
            userEmail: "<?= /* @noEscape */ $order->getCustomerEmail(); ?>",
            userFirstName: "<?= /* @noEscape */ $order->getCustomerFirstname() ? $order->getCustomerFirstname() :
            $billing->getFirstname(); ?>",
            userLastName: "<?= /* @noEscape */ $order->getCustomerLastname() ? $order->getCustomerLastname() :
            $billing->getLastname(); ?>",
            orderId: "<?= /* @noEscape */ $order->getId(); ?>",
            orderItems: <?= /* @noEscape */ $orderItemsFlattened; ?>
        }

        tracker.trackCheckout(orderFeed);

}catch(e){window.console && window.console.log(e)}}());
</script>
