<?php
  $viewModel = $block->getData('view_model');
?>

<div id="pr-write"></div>
<script>
  window.pwr = window.pwr || function() {
    (pwr.q = pwr.q || []).push(arguments);
  }
</script>
<script>
  pwr("render", {
    api_key: "<?= /* @noEscape */ $viewModel->getApiKey(); ?>",
    locale: "<?= /* @noEscape */ $viewModel->getLocale(); ?>",
    merchant_group_id: "<?= /* @noEscape */ $viewModel->getMerchantGroupId(); ?>",
    merchant_id: "<?= /* @noEscape */ $viewModel->getMerchantId(); ?>",
    components: {
      Write: 'pr-write'
    }
  });
</script>
