<?php
  $viewModel = $block->getData('view_model');
  $defaultReview = $viewModel->getMagentoDefaultReview();
?>
<?php if ($defaultReview != '1') {?>
<!-- start_review_render_code_widget_section -->
<div id="pr-questiondisplay" style="<?= $viewModel->getProductPageQuestionDisplay() ? '' : 'display: none;' ?>"></div>
<!-- end_review_render_code_widget_section -->

    <?php if (!$viewModel->getProductPageQuestionDisplay()): ?>
      <script>
        (function() {
          var qaTab = document.getElementById("tab-label-questiondisplay.tab");
          qaTab.setAttribute("style", "display:none;");
        })();
      </script>
    <?php endif; ?>
<?php } ?>
